"""add auth tables

Revision ID: 248f2949289c
Revises: 637848f507e4
Create Date: 2026-07-30 07:22:47.484489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248f2949289c'
down_revision = '637848f507e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kid', sa.String(length=12), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_key_id', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('administrator','updater')", name='ck_api_keys_role_valid'),
    sa.CheckConstraint('length(kid) = 12', name='ck_api_keys_kid_length'),
    sa.CheckConstraint('length(secret_hash) = 64', name='ck_api_keys_secret_hash_length'),
    sa.ForeignKeyConstraint(['created_by_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kid')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index('uq_api_keys_active_name', ['name'], unique=True, sqlite_where=sa.text('revoked_at IS NULL'))

    op.create_table('recovery_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kid', sa.String(length=12), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('length(kid) = 12', name='ck_recovery_keys_kid_length'),
    sa.CheckConstraint('length(secret_hash) = 64', name='ck_recovery_keys_secret_hash_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kid')
    )
    op.create_table('auth_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('kid', sa.String(length=12), nullable=True),
    sa.Column('actor_key_id', sa.Integer(), nullable=True),
    sa.Column('remote_addr', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['actor_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_events', schema=None) as batch_op:
        batch_op.create_index('ix_auth_events_created_at', ['created_at'], unique=False)

    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kid', sa.String(length=12), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('length(kid) = 12', name='ck_auth_sessions_kid_length'),
    sa.CheckConstraint('length(secret_hash) = 64', name='ck_auth_sessions_secret_hash_length'),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kid')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_auth_sessions_api_key_id', ['api_key_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_auth_sessions_api_key_id')

    op.drop_table('auth_sessions')
    with op.batch_alter_table('auth_events', schema=None) as batch_op:
        batch_op.drop_index('ix_auth_events_created_at')

    op.drop_table('auth_events')
    op.drop_table('recovery_keys')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index('uq_api_keys_active_name', sqlite_where=sa.text('revoked_at IS NULL'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
