"""Add ai_models, modalities and modality association tables

Revision ID: 637848f507e4
Revises: 
Create Date: 2026-07-28 18:55:37.887805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637848f507e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('price_in', sa.Float(), nullable=False),
    sa.Column('price_out', sa.Float(), nullable=False),
    sa.Column('context_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('context_tokens > 0', name='ck_ai_models_context_tokens_positive'),
    sa.CheckConstraint('price_in >= 0', name='ck_ai_models_price_in_non_negative'),
    sa.CheckConstraint('price_out >= 0', name='ck_ai_models_price_out_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_models_name'), ['name'], unique=True)

    op.create_table('modalities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ai_model_input_modalities',
    sa.Column('ai_model_id', sa.Integer(), nullable=False),
    sa.Column('modality_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ai_model_id'], ['ai_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modality_id'], ['modalities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ai_model_id', 'modality_id')
    )
    op.create_table('ai_model_output_modalities',
    sa.Column('ai_model_id', sa.Integer(), nullable=False),
    sa.Column('modality_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ai_model_id'], ['ai_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modality_id'], ['modalities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ai_model_id', 'modality_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_model_output_modalities')
    op.drop_table('ai_model_input_modalities')
    op.drop_table('modalities')
    with op.batch_alter_table('ai_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_models_name'))

    op.drop_table('ai_models')
    # ### end Alembic commands ###
